language: c

jobs:
  include:
    - os: osx
      osx_image: xcode10.1
      sudo: required

script:
  - id -a;pwd;ls -al
  - type -a sftp
  - type -a scp
  - java -version
  - sw_vers -productVersion
  - system_profiler SPSoftwareDataType
  - /Users/travis/build/zoff99/java_toxclient_example/circle_scripts/deps_macos.sh
  - /Users/travis/build/zoff99/java_toxclient_example/circle_scripts/java_jni_lib_macos.sh

after_success:
  - echo ls -al /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib
  - echo "xxxxxxxxxxxxxx"

