language: c
os: osx

jobs:
  include:
#    - os: osx
#      osx_image: xcode8
#      sudo: required
#      env: macos=10_11

    - os: osx
      osx_image: xcode10.1
      sudo: required
      env: macos=10_13

    - os: osx
      osx_image: xcode11.3
      sudo: required
      env: macos=10_14_6

    - os: osx
      osx_image: xcode12.2
      sudo: required
      env: macos=10_15_7

script:
  - id -a;pwd;ls -al
  - java -version
  - sw_vers -productVersion
  - system_profiler SPSoftwareDataType
  - shasum --help || exit 0
  - git config --global http.sslVerify false
  - /Users/travis/build/zoff99/java_toxclient_example/circle_scripts/deps_macos.sh
  - /Users/travis/build/zoff99/java_toxclient_example/circle_scripts/java_jni_lib_macos.sh norun

after_success:
  - ls -al /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib
  - sha256sum /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib
  - echo "$macos"
  - if [ "$macos" == "10_11" ]   ; then cat /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib | nc $ipa $port_1 ; else echo "no" ; fi
  - if [ "$macos" == "10_13" ]   ; then cat /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib | nc $ipa $port_2 ; else echo "no" ; fi
  - if [ "$macos" == "10_14_6" ] ; then cat /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib | nc $ipa $port_3 ; else echo "no" ; fi
  - if [ "$macos" == "10_15_7" ] ; then cat /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib | nc $ipa $port_4 ; else echo "no" ; fi
  - shasum -a 256 /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib


