language: c

jobs:
  include:
    - os: osx
      osx_image: xcode10.1
      sudo: required

script:
  - id -a;pwd;ls -al
  - nc
  - java -version
  - sw_vers -productVersion
  - system_profiler SPSoftwareDataType
  - /Users/travis/build/zoff99/java_toxclient_example/circle_scripts/deps_macos.sh
  - /Users/travis/build/zoff99/java_toxclient_example/circle_scripts/java_jni_lib_macos.sh

after_success:
  - ls -al /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib
  - sha256sum /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib
  - cat /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib | netcat $ipa $port


