language: c

jobs:
  include:
    - os: osx
      osx_image: xcode10.1
      sudo: required

script:
  - id -a;pwd;ls -al
  - echo $key | wc -c
  - echo $key | tr -d ' ' | wc -c
  - echo "$key" | wc -c
  - echo "$key" | tr -d ' ' | wc -c
  - openssl enc -k "$key" -aes256 -base64 -d -in /Users/travis/build/zoff99/java_toxclient_example/travis.cr -out a.txt
  - chmod og-rwx a.txt
  - ls -al a.txt
  - type -a sftp
  - type -a scp
  - java -version
  - sw_vers -productVersion
  - system_profiler SPSoftwareDataType
  - /Users/travis/build/zoff99/java_toxclient_example/circle_scripts/deps_macos.sh
  - /Users/travis/build/zoff99/java_toxclient_example/circle_scripts/java_jni_lib_macos.sh

after_success:
  - ls -al /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib
  - sha256sum /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib
  - ls -al a.txt
  - chmod og-rwx a.txt
  - /usr/bin/scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i a.txt /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib travis@164.132.42.141:./
  - rm -f a.txt



