strategy:
  matrix:
    linux:
      imageName: ubuntu-20.04
    mac:
      imageName: macOS-10.15
    windows:
      imageName: windows-2019

pool:
  vmImage: $(imageName)

- stage: stage1
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!

- stage: stage2
  jobs:
  - job: job2.1
    steps:
    - script: |
        gcc --version
      displayName: 'os version'


