name: MacOS CI

on:
  push:
    paths-ignore:
     - 'README.md'
#    tags:
#     - tags/*
  pull_request:
    paths-ignore:
     - 'README.md'
  schedule:
    - cron:  '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  macos-compile:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: install cliclick
      run:  brew install cliclick

    - name: install deps
      run:  brew install autoconf automake libtool

    - name: test java1
      run:  |
            type java
            java -version || exit 0
            /usr/libexec/java_home -V
            /usr/libexec/java_home -v 11
            export JAVA_HOME=$(/usr/libexec/java_home -v11)
            java -version
            $JAVA_HOME/bin/java -version
            $JAVA_HOME/bin/javac -version
            ls -al /usr/local/Cellar/openjdk/

    - name: cat jni headers1
      run:  |
            cat /usr/local/Cellar/openjdk/15.0.2/include/jni_md.h || exit 0

    - name: cat jni headers2
      run:  |
            cat /usr/local/Cellar/openjdk/15.0.2/include/jni.h || exit 0

    - name: install java
      run:  brew install java

    - name: test java2
      run:  |
            type java
            java -version || exit 1

    - name: test java3
      run:  |
            type javac
            javac -version || exit 1

    - name: macos-version1
      run: sw_vers -productVersion

    - name: macos-version2
      run: system_profiler SPSoftwareDataType

    - name: csrutil-status
      run: csrutil status || exit 0

    - name: notifications_off_01
      run: launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist || exit 0

    - name: notifications_off_02
      run: killall NotificationCenter || exit 0

    - name: compile
      run: |
           pwd
           ls -al /Users/runner/
           _HOME_="/Users/runner/"
           cliclick -m verbose m:12,34
           screencapture -T 42 -x -t png /Users/runner/screen01.png &
           screencapture -T 43 -x -t png /Users/runner/screen02.png &
           screencapture -T 43 -x -t png /Users/runner/screen03.png &
           screencapture -T 44 -x -t png /Users/runner/screen04.png &
           screencapture -T 45 -x -t png /Users/runner/screen05.png &
           screencapture -T 120 -x -t png /Users/runner/screen06.png &
           screencapture -T 240 -x -t png /Users/runner/screen07.png &
           screencapture -T 320 -x -t png /Users/runner/screen08.png &
           export _HOME_
           cd "$_HOME_"
           cd "$_SRC_"
           /Users/runner/work/java_toxclient_example/java_toxclient_example/circle_scripts/deps_macos.sh
           /Users/runner/work/java_toxclient_example/java_toxclient_example/circle_scripts/java_jni_lib_macos.sh

    - name: upload screenshots
      uses: actions/upload-artifact@v2
      with:
        name: macscreen
        path: |
          /Users/runner/screen*.png

    - name: upload artefacts
      uses: actions/upload-artifact@v2
      with:
        name: libs
        path: /Users/runner/work/artefacts/*


  windows-compile:
    runs-on: windows-latest
    steps:
      - name: Display the path
        run: echo %PATH%
        shell: cmd

      - name: java version
        run: set -x ; "$JAVA_HOME_11_X64/bin/java.exe" -version
        shell: bash

