name: MacOS JNI CI

on:
  push:
    paths-ignore:
     - 'README.md'
#    tags:
#     - tags/*
  pull_request:
    paths-ignore:
     - 'README.md'
  schedule:
    - cron:  '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  macos-compile:
    runs-on: macos-10.13
    steps:
    - uses: actions/checkout@v2
    - name: install cliclick
      run:  brew install cliclick

    - name: install deps
      run:  brew install autoconf automake libtool
