name: Nightly

on:
  push:
    paths-ignore:
     - 'README.md'
  schedule:
    - cron:  '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  windows-compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Display the path
        run: echo %PATH% ; echo $PATH
        shell: cmd

      - name: java version
        run: set -x ; "$JAVA_HOME_11_X64/bin/java.exe" -version
        shell: bash

      - name: java version with path
        run: set -x ; set PATH="$PATH;$JAVA_HOME_11_X64/bin" ; java.exe -version ; echo %PATH% ; echo $PATH
        shell: bash

      - name: java compile
        run: pwd;ls -al
        shell: bash



