name: Nightly

on:
#  push:
#    paths-ignore:
#     - 'README.md'
  schedule:
    - cron:  '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  macos-test-run:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2

    - name: Display the OS Version1
      run: sw_vers -productVersion

    - name: Display the OS Version2
      run: system_profiler SPSoftwareDataType

    - name: display java version
      run:  |
            type java
            java -version || exit 0
            /usr/libexec/java_home -V
            /usr/libexec/java_home -v 11
            export JAVA_HOME=$(/usr/libexec/java_home -v11)
            java -version
            $JAVA_HOME/bin/java -version
            $JAVA_HOME/bin/javac -version

    - name: java compile
      run:  |
            export JAVA_HOME=$(/usr/libexec/java_home -v11)
            export PATH="$JAVA_HOME/bin:$PATH"
            java -version
            javac -version
            cd trifa_desktop/app/src/main/java/
            ./do_compile.sh

    - name: java run
      run:  |
            export JAVA_HOME=$(/usr/libexec/java_home -v11)
            export PATH="$JAVA_HOME/bin:$PATH"
            java -version
            javac -version
            cd trifa_desktop/app/src/main/java/
            ./do_run.sh > trifa.log 2>&1 &
            sleep 80
            cat trifa.log
            cat trifa.log | grep "MainActivity:MyToxID:"

  windows-test-run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Display the OS Version
        run: systeminfo | findstr /C:"OS"
        shell: cmd

      - name: Display the path
        run: echo %PATH%
        shell: cmd

      - name: display java version
        run: set -x ; "$JAVA_HOME_11_X64/bin/java.exe" -version
        shell: bash

      - name: change path for java version
        run: |
             echo %JAVA_HOME%
             java -version
             javac -version
             where java.exe
             where javac.exe
        shell: cmd

      # C:\Program Files\Java\jdk-11.0.10+9/bin/java.exe

      - name: java compile
        run: |
             set JAVA_HOME=%JAVA_HOME_11_X64%
             set Path=%JAVA_HOME%\bin;%Path%
             java -version
             javac -version
             where java.exe
             where javac.exe
             cd trifa_desktop\app\src\main\java\
             dir
             do_compile.bat
        shell: cmd

      - name: java run
        run: |
             set JAVA_HOME=%JAVA_HOME_11_X64%
             set Path=%JAVA_HOME%\bin;%Path%
             java -version
             javac -version
             where java.exe
             cd trifa_desktop\app\src\main\java\
             START /B CMD /C CALL "do_run.bat" >trifa.log 2>&1
             echo "XXXXXXXXXX"
             ping -n 20 127.0.0.1 >NUL
             cat trifa.log
             cat trifa.log | find "MainActivity:MyToxID:"
        shell: cmd


