name: Nightly

on:
  push:
    paths-ignore:
     - 'README.md'
  schedule:
    - cron:  '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  windows-compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Display the OS Version
        run: systeminfo | findstr /C:"OS"
        shell: cmd

      - name: Display the path
        run: echo %PATH%
        shell: cmd

      - name: display java version
        run: set -x ; "$JAVA_HOME_11_X64/bin/java.exe" -version
        shell: bash

      - name: change path for java version
        run: |
             echo %JAVA_HOME%
             java -version
             javac -version
             where java.exe
             where javac.exe
        shell: cmd

      # C:\Program Files\Java\jdk-11.0.10+9/bin/java.exe

      - name: java compile
        run: |
             set JAVA_HOME=%JAVA_HOME_11_X64%
             set Path=%JAVA_HOME%\bin;%Path%
             java -version
             javac -version
             where java.exe
             where javac.exe
             cd trifa_desktop\app\src\main\java\
             dir
             do_compile.bat
        shell: cmd

      - name: java run
        run: |
             set JAVA_HOME=%JAVA_HOME_11_X64%
             set Path=%JAVA_HOME%\bin;%Path%
             java -version
             javac -version
             where java.exe
             cd trifa_desktop\app\src\main\java\
             START /B CMD /C CALL "do_run.bat"
             timeout /t 30 /nobreak
        shell: cmd

#            START /B "java.exe" -Djava.library.path="." -classpath ".;sqlite-jdbc-3.32.3.2.jar;webcam-capture-0.3.12.jar;bridj-0.7.0.jar;slf4j-api-1.7.2.jar;flatlaf-1.0.jar" com.zoffcc.applications.trifa.MainActivity

